parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    experimentalObjectRestSpread: true

env:
  node: true

rules:
  quotes: [1, "single"]
  semi: [1, "never"]
  semi-spacing: ["error", {"before": false, "after": true}]
  key-spacing: ["error", { "beforeColon": false, "afterColon": true }]
  rest-spread-spacing: ["error", "never"]
  func-call-spacing: ["error", "never"]
  no-tabs: 1
  eqeqeq: 1  
  no-alert: 2
  no-else-return: 2
  no-eval: 2
#  no-global-assign: 2
#  no-implicit-globals: 2
  no-implied-eval: 2 
  no-loop-func: 2
  no-redeclare: 2
  no-throw-literal: 2
  yoda: [2, "never"]  
  no-unused-vars: 2
  no-nested-ternary: 2

parser: babel-eslint

